#!/usr/bin/env python3
# Run the k8s dashboard locally

import subprocess

def kubectl(*args):
    return subprocess.run(('kubectl',) + args, text=True)

def run_dashboard():
    print('Spinning up Kubernetes Dashboard at https://localhost:8080/')
    print('Press ^C to exit\n')

    try:
        kubectl('-n', 'kubernetes-dashboard', 'port-forward', 'svc/kubernetes-dashboard', '8080:443')
    except KeyboardInterrupt:
        exit(0)

if __name__ == '__main__':
    run_dashboard()
